Models/gradeCalModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MissionThree.Models
{
    public class gradeCalModel
    {
        [Required]
        [Range(0,100)]
        public float assignments { get; set; }
        [Required]
        [Range(0, 100)]
        public float groupProjects { get; set; }
        [Required]
        [Range(0, 100)]
        public float quizzes { get; set; }
        [Required]
        [Range(0, 100)]
        public float exams { get; set; }
        [Required]
        [Range(0, 100)]
        public float intex { get; set; }
    }
}

Controllers/vController.cs
using Microsoft.AspNetCore.Mvc;
using MissionThree.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MissionThree.Controllers
{
    public class vController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public IActionResult gradeCal()
        {
            return View();
        }
        [HttpPost]
        public IActionResult gradeCal(gradeCalModel model)
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <meta charset="utf-8" />
    <link href="css/default.css" rel="stylesheet" />
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="icon" href="img/icon.jfif" />
</head>
<body>
    <nav>
        <a asp-controller="v" asp-action="Index">Home</a>
        <a asp-controller="v" asp-action="gradeCal">Calculator</a>
    </nav>
    <script src="js/Calculator.js"></script>
    <div>
        @RenderBody()
    </div>
    <script src="lib/bootstrap/js/bootstrap.js"></script>
    <script src="lib/jquery/jquery-3.6.0.min.js"></script>
</body>
</html>

Views/v/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mission Three";
}
<h1>Jerron Patterson</h1>
<img src="img/IMG_7395.jpg" />
<p>This was taken at a ballroom competition</p>
<br /><br />
<p>I hope to improve my ability to create novel solutions using code while in IS 413.</p>
<br />
<p>Future Job Options:</p>
<ul>
    <li>Consulting</li>
    <li>Developer</li>
    <li>Entrepreneur</li>
</ul>

Views/v/gradeCal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}
@model gradeCalModel;


<form method="post">
    <label>Assignments:</label>
    <input id="Asg" asp-for="assignments" /><br />
    <label>Group Project:</label>
    <input id="GP" asp-for="groupProjects" /><br />
    <label>Quizzes:</label>
    <input id="Qzz" asp-for="quizzes" /><br />
    <label>Exams:</label>
    <input id="Ex" asp-for="exams" /><br />
    <label>INTEX:</label>
    <input id="ITX" asp-for="intex" /><br />
    <input id="CalBtn" type="submit" value="Calculate Grade" />

    <div asp-validation-summary="All"></div>
</form>